### ISSUE TITLE
Add sizes to components

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#1090]
At times we need different sizes for components like buttons, inputs, grids etc. True, the same can be achieved trough customization, but at times we need to apply said size only to specific components. Thus, we need predefined abstract sizes (small, medium, large etc).

**Describe the solution you would like to see implemented**

Provide class names for buttons, inputs, grid, say button-sm, input-lg etc.

**Describe the alternatives you have considered**

There is no viable alternative than providing built in classes. Customizing the components outside of the scope of the framework would yield inconsistent results at best.

**Additional context**

Applies to:

* [x] Grid / Treelist telerik/kendo-themes-private#6
* [x] Pager https://github.com/telerik/kendo-themes/issues/4002
* [x] Button
* [x] Toolbar https://github.com/telerik/kendo-themes/issues/3294
* [x] Generic inputs
* [x] Combobox
* [x] Dropdown
* [x] Autocomplete
* [x] Numeric
* [x] Date / Time picker
* [x] Colorpicker
* [x] Multiselect
* TBA

**Comment by eeasss** [comment]
Any updates in this one? Where are we, do we have designs ready?

**Comment by Juveniel** [comment]
Done with v6.0.0 of the themes, where the Pager, Toolbar and Grid sizing is implemented.
