### ISSUE TITLE
Switch to index imports

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#1218]
As a prerequisite for the migration / support to [sass module system](https://sass-lang.com/blog/the-module-system-is-launched), we'll switch to index import. In a nutshell, each component directory will be like a module and contain all files needed for it (minus the dependencies).

Instead of the current `COMPONENT_NAME.scss`, we'll have `COMPONENT_NAME/_index.scss` file to import. The syntax changes a bit when importing:

```scss
// current
@import "grid.scss";

// new
@import "grid/"; // for dart-sass
@import "grid/_index.scss"; // for node-sass
```

Note: we could write just `@import "grid"` for dart sass, but I want to make immediately obvious that we are importing a directory!

- [x] switch to module imports (@joneff, #1219)
- [x] update kendo-jquery docs (@Juveniel https://github.com/telerik/kendo/pull/10622)
- [ ] update kendo-vue docs (@PreslavKozovski)
- [x] update telerik-blazor docs (@TeyaVes)
- [x] update kendo-angular docs (@JoomFX telerik/k2#198)
- [x] update kendo-react docs (@silviyaboteva, telerik/katana#253)

**Updating the docs**

Here is what I want to change in the docs:

* anywhere that we are referring to `@progress/kendo-theme-*/scss/all.scss` to have it to point to `dist/all.scss`. That file contains a flattened version of the theme and compiles much much faster than `scss/all.scss`, regardless of the compiler.
* anywhere that we have `COMPONENT_NAME.scss` to have it changed to `COMPONENT_NAME/_index.scss`.
* Alternatively, you could explain on the styling overview page that depending on the sass compiler flavour (node vs dart), you could have it both ways. Again, make sure that if you are showing the "short" syntax, you end the import with / e.g. `@import "spreadsheet/";`, instead of   `@import "spreadsheet";`. Please don't forget the trailing semi-colon!

/cc @Xizario @tapopov @Raisolution @tsvetomir @eeasss @hadjieva  @nenchef  @ivanchev -- please have this in mind, the next time we are creating / updating an app that references the stylesheets as sass files. Feel free to add anything.
/cc @telerik/kendo-front-end Do share your thoughts!

**Comment by silviyaboteva** [comment]
The react docs update is on PR: https://github.com/telerik/katana/pull/253. Please ping me when it should be merged and get live.

**Comment by joneff** [comment]
Possibly related to #1041
