### ISSUE TITLE
v5 prerequisites

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#1220]
Migrating to sass modules requires some refactoring before we begin the migration

* [x] switch to _index.scss imports (@joneff #1218)
* [x] switch to `@include fill` instead of `@include appearance` (#1221)
* [x] rework functions default value (@joneff #1222)
* [x] rework mixins with default value (@joneff #1242)
* [x] extract fonts as a module (#1223)
* [x] merge `edit-form` and `common/forms` to forms module (@JoomFX  #1224)
* [ ] rework styling module (#1225)
* TBA

**Comment by montella1507** [comment]
@joneff  why is your prerequisites  #1280 in next patch version<

https://github.com/telerik/kendo-themes/issues/1257

It breaks things :-(
