### ISSUE TITLE
ColorPicker Styles Revision

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-themes#2202]
<details>

More details can be found in the following links:
* Aha: https://progresssoftware.aha.io/features/BLZR-111
* Parent: telerik/web-components-planning#7
* Design: telerik/kendo-ux-private#319

</details>

**Description**

- Verify current rendering
    - Currently, palettes include inline style for sizing of the table cells. Could this be made in the themes?
    - Check if there are known downsides with the current rendering in react/angular 
-  Verify the design is followed and everything is applied in the themes
    - ClearButton, PaletteView, GradientView match the design, along with metrics in the design

**Implementation status:**
* [x] themes (#2852)
* [ ] kendo-jquery (telerik/kendo#13313)
* [ ] angular (telerik/kendo-angular-inputs#578)
* [ ] blazor (telerik/blazor#2386)

Please, add a comment with the status of the themes and the rendering that is to be followed in Blazor.

**_Release: 27th October /Iteration 1/_**

**Stakeholders**
- Angular - @preslavapetrova1 @Raisolution 
- Blazor - @jivanova 
- jQuery - @Iankodj 
- React - @InaGlushkova

**Comment by Juveniel** [comment]
Currently. the ColorPalette, ColorGradient and ColorPicker styles are implemented in one module in the themes. With this task, we will split them in separate component modules and create reference rendering for the three components.

## ColorPalette Rendering

```html
<div class="k-widget k-colorpalette">
    <div class="k-colorpalette-table-wrap">
        <table class="k-colorpalette-table k-palette">
            <tbody>
                <tr>
                    <td class="k-colorpalette-item k-item" style="background-color: rgb(0, 0, 0);"></td>
                    <td class="k-colorpalette-item k-item" style="background-color: rgb(127, 127, 127);"></td>
                </tr>                
            </tbody>
        </table>
    </div>
</div>
```

## ColorGradient Rendering

```html
<div class="k-widget k-colorgradient">

    <!-- Header -->
    <div class="k-colorgradient-header k-hstack">
        <div class="k-colorgradient-header-actions k-colorgradient-header-actions-start">
            <div class="k-widget k-button-group">
                <button class="k-button k-icon-button k-flat k-state-selected">
                    <span class="k-button-icon k-icon k-i-saturation"></span>
                </button><button class="k-button k-icon-button k-flat">
                    <span class="k-button-icon k-icon k-i-palette"></span>
                </button>
            </div>
        </div>
        <div class="k-spacer"></div>
        <div class="k-colorgradient-header-actions k-colorgradient-header-actions-end">
            <span class="k-colorgradient-preview-color k-color-preview" style="background-color: rgba(0,0,0, 0.5)"></span>
            <span class="k-colorgradient-current-color k-color-preview" style="background-color: #FF6358;"></span>
        </div>
    </div>

    <!-- Canvas  -->
    <div class="k-colorgradient-canvas k-hstack">

        <!-- Value -->
        <div class="k-colorgradient-hsv-rectangle" style="background: rgb(255, 0, 0);">
            <div class="k-hsv-gradient">
                <div class="k-draghandle" style="top: 50px; left: 73px;"></div>
            </div>
        </div>

        <!-- Canvas Controls -->
        <div class="k-colorgradient-hsv-controls k-hstack">
            <div class="k-widget k-slider k-slider-vertical k-hue-slider k-colorgradient-slider">
                <div class="k-slider-wrap" style="position: relative;">
                    <div class="k-slider-track" style="height: 180px;">
                        <div class="k-slider-selection" style="height: 0px;"></div>
                        <a class="k-draghandle" style="bottom: -8px;"></a>
                    </div>
                </div>
            </div>

            <div class="k-widget k-slider k-slider-vertical k-alpha-slider k-colorgradient-slider">
                <div class="k-slider-wrap" style="position: relative;">
                    <div class="k-slider-track" style="background: linear-gradient(to top, transparent, rgb(255, 0, 0));">
                        <div class="k-slider-selection" style="height: 180px;"></div>
                        <a class="k-draghandle" style="bottom: 172px;"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Color Inputs -->
    <div class="k-colorgradient-inputs k-hstack">
        <div class="k-vstack">
            <button class="k-colorgradient-toggle-mode k-button k-icon-button k-flat">
                <span class="k-button-icon k-icon k-i-arrows-kpi"></span>
            </button>
        </div>
        <div class="k-vstack">
            <span class="k-widget k-numerictextbox">
                <span class="k-numeric-wrap">
                    <input type="tel" class="k-input k-formatted-value" value="132">
                </span>
            </span>
            <div>R</div>
        </div>

        <div class="k-vstack">
            <span class="k-widget k-numerictextbox">
                <span class="k-numeric-wrap">
                    <input type="tel" class="k-input k-formatted-value" value="132">
                </span>
            </span>
            <div>G</div>
        </div>

        <div class="k-vstack">
            <span class="k-widget k-numerictextbox">
                <span class="k-numeric-wrap">
                    <input type="tel" class="k-input k-formatted-value" value="132">
                </span>
            </span>
            <div>B</div>
        </div>

        <div class="k-vstack">
            <span class="k-widget k-numerictextbox">
                <span class="k-numeric-wrap">
                    <input type="tel" class="k-input k-formatted-value" value="1.00">
                </span>
            </span>
            <div>A</div>
        </div>
    </div>

    <!-- Color Contrast Tool  -->
    <div class="k-colorgradient-color-contrast k-vbox">
        <div class="k-contrast-ratio">
            <span class="k-contrast-ratio-text">Contrast ratio: 7.1</span>
            <span class="k-contrast-validation k-text-success">
                <span class="k-icon k-i-check"></span>
                <span class="k-icon k-i-check"></span>
            </span>
        </div>
        <div>
            <span>AA: 4.5</span>
            <span class="k-contrast-validation k-text-success">
                Pass
                <span class="k-icon k-i-check"></span>
            </span>
        </div>
        <div>
            <span>AAA: 7.0</span>
            <span class="k-contrast-validation k-text-error">
                Fail
                <span class="k-icon k-i-close"></span>
            </span>
        </div>
    </div>

    <!-- Footer Actions  -->
    <div class="k-colorgradient-footer k-actions k-hstack k-justify-content-end">
        <button class="k-dialog-close k-button">Cancel</button>
        <button class="k-dialog-update k-button k-primary">Apply</button>
    </div>
</div>
```

**Comment by Juveniel** [comment]
@preslavapetrova1, @jivanova, @Iankodj, @silviyaboteva I would like to ask your opinion on the following:

Based on the above rendering we can have: standalone ColorPalette, standalone ColorGradient, ColorPicker that includes header, footer and views (ColorPalette/ColorGradient) in its popup. However, do we want to support a scenario where we can render the ColorGradient/ColorPalette including the header and footer standalone (not in a popup) like a flat variant ? Have you considered this scenario ?

In general, if we would like to support this, we can render the ColorPicker Popup contents in an element on the page with a specific class that applies the container styles. However, this will require specific ColorPicker component API that toggles this behavior and controls how the value is applied perhaps. IMO we should avoid this as this will create one more deviation in the rendering.

**Comment by preslavapetrova1** [comment]
Both the header and footer include functionalities, which should be present when the components are standalone i.e. clear button, prev/current colors, apply/cancel action buttons, excluding the views option.

**Comment by Iankodj** [comment]
@preslavapetrova1 The design shows the dual mode in both standalone variants why excluding it? 

On the jQuery site, we are forced to include the dual mode in the FlatColorPicker (i.e., ColorGradient). Otherwise, we will need to entirely rewrite the ColorPicker and introduce a lot of breaking changes.
