### ISSUE TITLE
Investigate Color Distance in the Default/Boostrap/Material Theme

### ISSUE THREAD

**Issue by eeasss** [telerik/kendo-themes#2234]
It seems that the default theme uses more colors that what our color palette would suggest.

@joneff is to sync with the designers to identify the deviations and reduce the usages to the colors available in the palette.

Done

* [x] Use correct styling for input buttons (#2296)
* [x] Reduce color distance in chart (#2303)
* [x] Remove redundant upload variables (#2285)
* [x] Reduce color distance in progressbar and slider (#2306)
* [x] Use `$subtle-text` variable for styling cards styling (#2330)
* [x] Use subtle-text variable in adaptive scheduler styling (#2329) 
* [x] Use `$subtle-text` for calendar styling (#2328)
* [x] Use `$subtle-text` variable for upload styling (#2332)
* [x] Use `$subtle-text` variable for input styling (#2320)
* [x] Use `$subtle-text` variable for tabstrip styling (#2334)
* [x] Use subtle text variable for colorpicker styling (#2338)
* [x] Use subtle text variable for menu styling (#2338)
* [x] Use subtle text variable for split button styling (#2338)
* [x] Remove opacity of window titlebar actions in material theme (#2338)
* [x] Use correct colors for multiselect in material theme (#2338)
* [x] Improve chip icon and remove icon colors in material theme (#2338)
* [x] use `$subtle-text` variable for rating styling (#2340)
* [x] use `$subtle-text` variable for form styling (#2340)
* [x] use correct color determination for `$app-bg` (#2340)
* [x] use correct color determination for `$popup-bg` (#2340)
* [x] update breadcrumb styles to match material and bootstrap design (#2340)
* [x] update switch styles to match material and bootstrap designs  (#2341)
* [x] Remove duplicated drag drop styles (#2342)
* [x] reduce colors used by image editor (#2354)
* [x] use subtle-text and disabled-text variables for stepper styling (#2353)
* [x] bootstrap-theme: replace usages of darken with shade (#2352)
* [x] classic-theme: replace usages of darken with shade (#2352)
* [x] default-theme: replace usages of darken with shade (#2352)
* [x] material-theme: replace usages of darken with shade  (#2352)

**Comment by eeasss** [comment]
This item will get more specific once we setup the foundations of the Kendo Front-End docs and with base variables per theme available.
