### ISSUE TITLE
Prefix and Suffix support for Inputs

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-themes#2252]
Part of: Inputs Epic, [the Form Design Guidelines](https://xd.adobe.com/view/3e59e083-312d-4d76-b263-aab6dfd843c0-6b0a/specs/).
Related to: https://github.com/telerik/kendo-themes/issues/2200

**Description**

Add support for prefix and suffix containers in all input-based components where the built-in icons can be placed (e.g clear icon, validation error icon, custom icon, etc.). A similar implementation is already available for the [the TextBox](https://github.com/telerik/kendo-themes/blob/develop/tests/visual/output/default/textbox.png).

**Tasks**

- [x] Agree upon a unified rendering for all targeted components.
- [x] Utilize the existing `.k-input-prefix` and `.k-input-suffix` classes and integrate them in all input-based components.
- [x] Refactor existing tests and create new ones.

**Comment by svdimitr** [comment]
Made public in: https://feedback.telerik.com/themes/1511305-add-custom-icons-support-for-all-input-components

**Comment by joneff** [comment]
Part of component options.

shipped with 6f45cf0e1c4aeeca31cf8607e7f5b16f51dec598
