### ISSUE TITLE
Pickers issues related to the new styling options

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-themes#3105]
- [x] TimePicker height in small size is wrong when dateInput is enabled. 
Configuration:
  $("#timepicker1").kendoTimePicker({
                        dateInput: true,
                        size: "small"
                    });
Result: Height is 30px; Expected: 26px
- [x] There isn't visual indication when TimePicker and DateInput are focused
- [x] Pickers don't look good in large size in Bootstrap theme:
![bootstrap-pickers](https://user-images.githubusercontent.com/3844466/147226719-dfe525a0-ab5a-4631-ae43-cdf7161972b6.PNG)
- [ ] Pickers don't look good in large size in Material theme:
![material-pickers](https://user-images.githubusercontent.com/3844466/147226659-c7b2723e-e2f0-41a0-9984-81a8651a4b17.PNG)
- [x] DateTimePicker(datetimepicker/component-type)  modern view is broken:
![modern](https://user-images.githubusercontent.com/3844466/147227334-a9e4672c-291a-426a-a567-faa6afa5a096.PNG)
- [x] TimePicker moder view could be improved - it would be more readable if there is distance between Hour/Minute/AM/PM text and the digits. Currently, the text overlaps the digits:
![timepicker](https://user-images.githubusercontent.com/3844466/147228079-4065518d-f321-413a-a088-cabbb64337c1.PNG)
- [x] There is flickering while timepicker is opening if popup is displayed above the picker(timepicker/api - resize browser's window to force the popup show above the input)
- [x] DateRangePicker seems broken
![range](https://user-images.githubusercontent.com/3844466/147239257-52ece757-0958-4cce-932b-590d37536445.PNG)
- [x] There is a space between pickers's popup button and input's border:
![picker4](https://user-images.githubusercontent.com/3844466/147240086-b509ebfb-da1a-4fdb-9666-d5f95061b076.PNG)
