### ISSUE TITLE
Adaptive rendering for pickers

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-themes#3536]
**Describe the solution you would like to see implemented**

Aha link: https://progresssoftware.aha.io/features/BLZR-282
Design link: https://github.com/telerik/web-components-ux/issues/405

The scope of the task are the date pickers and their inner components.

- [x] Consider bottom drawer position feature (if drawer should be used in the adaptive scenario)
- [x] Adaptive Calendar 
- [x] Adaptive DatePicker
- [x] Adaptive DateTimePicker
- [x] Adaptive DateRangePicker
- [x] Adaptive TimePicker

**Additional context**

Needs front-end in PI 1 of R3 2022. Blazor team starts in PI2.

Pioneer team will be Blazor, but the task is part of a cross team planning: https://github.com/telerik/web-components-planning/issues/62

**Comment by joneff** [comment]
Created a PR for this. Using actionsheet instead of drawer, but that's a minor detail.

**Comment by radkostanev** [comment]
Reopening this as the following items are pending:

- [ ] `TimeSelector` does not render properly when nested inside a `.k-animation-container` element: https://dojo.telerik.com/OBADAXOb/2
- [ ] `DateTimePicker` appears cropped and positioned incorrectly: https://dojo.telerik.com/ADADOpAn
