### ISSUE TITLE
Migrate less themes to sass-based swatches

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#994]
For each less theme, create a sass theme based swatch:

Themes based on less-type-default: when migrating, those should be based on kendo-theme-classic. We should add dark swatches were applicable.
* [x] default - classic-main
* [x] black - classic-opal-dark
* [x] blue opal - classic-opal
* [x] moonlight - classic-moonlight
* [x] silver - classic-silver
* [x] uniform - classic-uniform

Themes based on less-type-bootstrap: when migrating, those should be based on kendo-theme-bootstrap. We should add dark swatch.
* [x] bootstrap 3 - bootstrap-3
* [x] new: bootstrap 3 dark - bootstrap-3-dark

Themes based on less-type-fiori: fiori is a specific theme and requires dedicated theme based on the latest Fiori design guidelines.
* fiori - N/A

Themes based on less-type-flat: when migrating, those should be based on kendo-theme-bootstrap. We should add dark swatch. We'll need design assistance.
* [x] flat - bootstrap-turquoise
* [x] new: flat dark - bootstrap-turquoise-dark

Themes based on less-type-highcontrast: that should be based on new theme.
* [x] highcontrast - classic-lavender-dark
* [x] new: highcontrast light - classic-lavender

Themes based on less-type-material: when migrating, those should be based on kendo-theme-material.
* [x] material - material-main
* [x] material black - material-main-dark

Themes based on less-type-metro: we don't have a sass theme based on metro design language.
* [x] metro - classic-metro
* [x] metro black - classic-metro-dark

Themes based on less-type-nova: when migrating, those should be based on kendo-theme-material. We should add dark swatch.
* [x] nova - material-nova

Themes based on less-type-office365: we should redirect to the new fluent theme successor:
* [x] office365 - fluent-main

**Describe the alternatives you have considered**
There are no alternatives
